// Emit the TOP2013 outer-planet analytic series (ephem.js 06-normal) as Rust.
//
// Decoded from ephem.js's evaluator `w`: each coeffs[element][power] is a flat list of 4-number terms
// (mult, Ccos, Csin, period_yr); the period is unused. The argument is mult·DMU·t (t = millennia from
// J2000), DMU = 0.359536228504931 (the Jupiter–Saturn great-inequality frequency). For element L the
// (power 1, mult 0) term is dropped and the mean motion mm·t is added instead, then L is wrapped.
// element_l(t) = Σ_power t^power · Σ_term [Ccos·cos(mult·DMU·t) + Csin·sin(mult·DMU·t)]   (+ mm·t for L)
// This reproduces ephem.js's TOP2013 .orbital() to ~1e-13. (verified by tools/.../decode.js)

global.THREE = { Matrix3: function () { this.set = function () { return this; }; }, Vector3: function (x, y, z) { this.x = x; this.y = y; this.z = z; this.applyMatrix3 = function () { return this; }; } };
global.Orbit = function (o) { Object.assign(this, o); };
global.CYCLE = (x) => { const t = 2 * Math.PI; return x - t * Math.floor(x / t); };
const fs = require("fs"), vm = require("vm");
vm.runInThisContext(fs.readFileSync("top2013_normal.js", "utf8"));
const TOP = globalThis.top2013;

const MM = { jup: 529.6909622785881, sat: 213.2990811942489, ura: 74.78166163181234, nep: 38.13297236217556 };
const PLANETS = [["jup", "JUP"], ["sat", "SAT"], ["ura", "URA"], ["nep", "NEP"]];
const fnum = (x) => (x === 0 ? "0.0" : x.toExponential(16));

const lines = [
  "// @generated by tools/ephemeris-data/gen_top.js from TOP2013 (ephem.js 06-normal, MIT). Do not edit.",
  "// Analytic Poisson series for the outer planets; reproduces the source theory to ~1e-13. See top2013.rs.",
  "#![allow(clippy::excessive_precision, clippy::unreadable_literal, clippy::approx_constant, clippy::type_complexity)]",
  "",
  "pub struct TopPlanet {",
  "    pub mm: f64,                                       // mean motion (rad / 1000 yr), added to L",
  "    pub elems: [&'static [&'static [(i32, f64, f64)]]; 6], // [a,L,k,h,q,p][power][term=(mult,Ccos,Csin)]",
  "}",
  "",
];

let totalTerms = 0;
for (const [key, RKEY] of PLANETS) {
  const c = TOP[key].coeffs;
  lines.push(`pub static ${RKEY}: TopPlanet = TopPlanet {`);
  lines.push(`    mm: ${fnum(MM[key])},`);
  lines.push("    elems: [");
  for (let el = 0; el < 6; el++) {
    lines.push("        &[ // element " + "aLkhqp"[el]);
    for (let f = 0; f < c[el].length; f++) {
      const m = c[el][f], terms = [];
      for (let k = 0; k < m.length; k += 4) {
        const id = Math.round(m[k]), cc = m[k + 1], cs = m[k + 2];
        terms.push(`(${id},${fnum(cc)},${fnum(cs)})`);
        totalTerms++;
      }
      lines.push("            &[" + terms.join(",") + "],");
    }
    lines.push("        ],");
  }
  lines.push("    ],");
  lines.push("};");
  lines.push("");
}

const dst = "../../crates/solar-ephemeris/src/top2013_data.rs";
fs.writeFileSync(dst, lines.join("\n") + "\n");
console.log(`wrote ${dst}  (${(fs.statSync(dst).size / 1024).toFixed(0)} KB, ${totalTerms} terms across 4 giants)`);
