// Generated by tools/prepare_atmosphere_incident.mjs. Numerical reference fields, not imagery.
export const INCIDENT_FIELDS=Object.freeze({
  "Earth": {
    "path": "../data/optics/earth-incident-v1.f32",
    "bytes": 1201200,
    "sha256": "4762cc9e49c98c292b412555c75867fce235aaa5f8f8165c78fd593020f06639",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "0a3fe3c7688556331ebfc2725d533472751eeb498479dcc7d1f3a34390675e9d",
    "domain": {
      "minHeightKm": 0,
      "maxHeightKm": 16,
      "quadratic": true
    },
    "generator_sha256": "13a66c6c391081332a79d03e2f21f0e476779efa6a5c5564b726cb1c0015bec4",
    "generator_source_sha256": "10b3284023e6a8f82eb9fac95d1b2cc3e75ceec720ce8fb89730d041f8cc6ee7",
    "solver_source_sha256": "71be7ee8dafe8cbe3c6f544c064169a4ac49d9ca396b4200beb67e1bb098c320",
    "profile_source_sha256": "825e97ea90fdc5e23266f61df5f9abeab0a6149d7dfb95c64220b08b0796df2c",
    "field_source_sha256": "cea91103472cbf13a2306e209ab0b68f9f0526516e537e7236e11082e0a510b9",
    "browser_version": "Chrome/151.0.7922.174",
    "dimensions": [
      385,
      65,
      3
    ],
    "format": "little-endian-rgba32f-bend-columns-v1"
  },
  "Mars": {
    "path": "../data/optics/mars-incident-v1.f32",
    "bytes": 1201200,
    "sha256": "bd22c2568cac1dfcc970501e7c92af734eb089c6a9b52700cc70de46b1d31311",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "133be6dfe9ff85c742be6518ab81b3ea1f4d272863ff5e1a8ac7435423e36e48",
    "domain": {
      "minHeightKm": -24,
      "maxHeightKm": 24,
      "quadratic": false
    },
    "generator_sha256": "13a66c6c391081332a79d03e2f21f0e476779efa6a5c5564b726cb1c0015bec4",
    "generator_source_sha256": "10b3284023e6a8f82eb9fac95d1b2cc3e75ceec720ce8fb89730d041f8cc6ee7",
    "solver_source_sha256": "71be7ee8dafe8cbe3c6f544c064169a4ac49d9ca396b4200beb67e1bb098c320",
    "profile_source_sha256": "825e97ea90fdc5e23266f61df5f9abeab0a6149d7dfb95c64220b08b0796df2c",
    "field_source_sha256": "cea91103472cbf13a2306e209ab0b68f9f0526516e537e7236e11082e0a510b9",
    "browser_version": "Chrome/151.0.7922.174",
    "dimensions": [
      385,
      65,
      3
    ],
    "format": "little-endian-rgba32f-bend-columns-v1"
  }
});
