// Generated by tools/prepare_atmosphere_columns.mjs. Numerical density columns, not imagery.
export const ATMOSPHERE_COLUMN_FIELDS=Object.freeze({
  "Earth": {
    "path": "../data/optics/earth-columns-v1.f32",
    "dimensions": [
      512,
      512,
      2
    ],
    "bytes": 2097152,
    "sha256": "85605fa0d75feb5186e5b812054bef730726668c3690a2b0cecc592dd50c4893",
    "format": "little-endian-rg32f-outward-columns-v1",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "e15e53579417f828a4f02b401d2c9ddebd78c6f956f5177d1def336ac7d7bed8",
    "generator_source_sha256": "6c7c90d4a4b72fc4d9c38bdb191889780e2f3a2cf44375cfe00f87c82c2fb48c",
    "field_source_sha256": "73cf95a02573a6807cacb9c119edfcc645e4f8e918d0f530c47c0c31e077ed3d",
    "solver_source_sha256": "282d74036c31b418ca8e1e43f9fdb4f975cf3ec03e3217da801d54ec945aa635",
    "profile_source_sha256": "b8ad270b14c4ef16affc7c31bd7fb5111895bc9cc6332cbe7c8c171d4582b965"
  },
  "Mars": {
    "path": "../data/optics/mars-columns-v1.f32",
    "dimensions": [
      512,
      512,
      2
    ],
    "bytes": 2097152,
    "sha256": "12ca78aa470ecb4191c450fa3c1981a48a0f9a049be628473929dfd2f7d8d895",
    "format": "little-endian-rg32f-outward-columns-v1",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "28e25e74130b1a426f07004ebdc66ca6c8f1094433f305302dab4c7338b15d7e",
    "generator_source_sha256": "6c7c90d4a4b72fc4d9c38bdb191889780e2f3a2cf44375cfe00f87c82c2fb48c",
    "field_source_sha256": "73cf95a02573a6807cacb9c119edfcc645e4f8e918d0f530c47c0c31e077ed3d",
    "solver_source_sha256": "282d74036c31b418ca8e1e43f9fdb4f975cf3ec03e3217da801d54ec945aa635",
    "profile_source_sha256": "b8ad270b14c4ef16affc7c31bd7fb5111895bc9cc6332cbe7c8c171d4582b965"
  }
});
