// Generated by tools/prepare_atmosphere_incident.mjs. Numerical reference fields, not imagery.
export const INCIDENT_FIELDS=Object.freeze({
  "Earth": {
    "path": "../data/optics/earth-incident-v1.f32",
    "bytes": 1201200,
    "sha256": "4762cc9e49c98c292b412555c75867fce235aaa5f8f8165c78fd593020f06639",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "e15e53579417f828a4f02b401d2c9ddebd78c6f956f5177d1def336ac7d7bed8",
    "domain": {
      "minHeightKm": 0,
      "maxHeightKm": 16,
      "quadratic": true
    },
    "generator_sha256": "5eeaff5c04bbdd67520c219fb8b264563c8640728d2c1abb56fa368db629126f",
    "generator_source_sha256": "10b3284023e6a8f82eb9fac95d1b2cc3e75ceec720ce8fb89730d041f8cc6ee7",
    "solver_source_sha256": "282d74036c31b418ca8e1e43f9fdb4f975cf3ec03e3217da801d54ec945aa635",
    "profile_source_sha256": "feb46692e6e2ad582350822ff5b01a582fdc832ec75e5a547b77408be509b802",
    "field_source_sha256": "cea91103472cbf13a2306e209ab0b68f9f0526516e537e7236e11082e0a510b9",
    "browser_version": "Chrome/151.0.7922.174",
    "dimensions": [
      385,
      65,
      3
    ],
    "format": "little-endian-rgba32f-bend-columns-v1"
  },
  "Mars": {
    "path": "../data/optics/mars-incident-v1.f32",
    "bytes": 1201200,
    "sha256": "bd22c2568cac1dfcc970501e7c92af734eb089c6a9b52700cc70de46b1d31311",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "28e25e74130b1a426f07004ebdc66ca6c8f1094433f305302dab4c7338b15d7e",
    "domain": {
      "minHeightKm": -24,
      "maxHeightKm": 24,
      "quadratic": false
    },
    "generator_sha256": "5eeaff5c04bbdd67520c219fb8b264563c8640728d2c1abb56fa368db629126f",
    "generator_source_sha256": "10b3284023e6a8f82eb9fac95d1b2cc3e75ceec720ce8fb89730d041f8cc6ee7",
    "solver_source_sha256": "282d74036c31b418ca8e1e43f9fdb4f975cf3ec03e3217da801d54ec945aa635",
    "profile_source_sha256": "feb46692e6e2ad582350822ff5b01a582fdc832ec75e5a547b77408be509b802",
    "field_source_sha256": "cea91103472cbf13a2306e209ab0b68f9f0526516e537e7236e11082e0a510b9",
    "browser_version": "Chrome/151.0.7922.174",
    "dimensions": [
      385,
      65,
      3
    ],
    "format": "little-endian-rgba32f-bend-columns-v1"
  }
});
