// Generated by tools/prepare_atmosphere_columns.mjs. Numerical density columns, not imagery.
export const ATMOSPHERE_COLUMN_FIELDS=Object.freeze({
  "Earth": {
    "path": "../data/optics/earth-columns-v1.f32",
    "dimensions": [
      512,
      512,
      2
    ],
    "bytes": 2097152,
    "sha256": "85605fa0d75feb5186e5b812054bef730726668c3690a2b0cecc592dd50c4893",
    "format": "little-endian-rg32f-outward-columns-v1",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "0a3fe3c7688556331ebfc2725d533472751eeb498479dcc7d1f3a34390675e9d",
    "generator_source_sha256": "6c7c90d4a4b72fc4d9c38bdb191889780e2f3a2cf44375cfe00f87c82c2fb48c",
    "field_source_sha256": "dba3c80adf95a7d8e0ea49afd537c6a324bd9f601bd503d4bfbbb2d1ce5b963d",
    "solver_source_sha256": "e1ddf2ac22c3af44c98fda3118fbc9a51c1d70e100591b2ee67b6f37766f357c",
    "profile_source_sha256": "825e97ea90fdc5e23266f61df5f9abeab0a6149d7dfb95c64220b08b0796df2c"
  },
  "Mars": {
    "path": "../data/optics/mars-columns-v1.f32",
    "dimensions": [
      512,
      512,
      2
    ],
    "bytes": 2097152,
    "sha256": "12ca78aa470ecb4191c450fa3c1981a48a0f9a049be628473929dfd2f7d8d895",
    "format": "little-endian-rg32f-outward-columns-v1",
    "profile_encoding": "atmosphere-profile-binary32-v1",
    "profile_sha256": "133be6dfe9ff85c742be6518ab81b3ea1f4d272863ff5e1a8ac7435423e36e48",
    "generator_source_sha256": "6c7c90d4a4b72fc4d9c38bdb191889780e2f3a2cf44375cfe00f87c82c2fb48c",
    "field_source_sha256": "dba3c80adf95a7d8e0ea49afd537c6a324bd9f601bd503d4bfbbb2d1ce5b963d",
    "solver_source_sha256": "e1ddf2ac22c3af44c98fda3118fbc9a51c1d70e100591b2ee67b6f37766f357c",
    "profile_source_sha256": "825e97ea90fdc5e23266f61df5f9abeab0a6149d7dfb95c64220b08b0796df2c"
  }
});
