// GENERATED by tools/generate_moons.py — do not edit.
// Static 3-D dependency: the Focus control and accessible positions list promise these
// 21 curated moons on first entry; optional geography and star enrichment remain lazy.
// This module carries identity only — name, parent, size, period, appearance. The weekly
// element knots are ~99% of the data and live in the lazily imported moonelements.js, so
// widening the validated window cannot put a megabyte on the first-paint path.
//
// The 21 major moons (Jupiter 4, Mars 2, Neptune 3, Saturn 7, Uranus 5) — every satellite with a mean radius of at
// least 150 km, plus Mars's two. Osculating elements from JPL Horizons, PLANETOCENTRIC and
// already referred to the ecliptic J2000 plane, so they need no frame rotation: they are in
// the renderer's own frame. See tools/ephemeris-data/moons/README.md for why the elements
// come from Horizons rather than from JPL's satellite mean-elements table.
//
// ACCURACY — the renderer linearly interpolates weekly modified-equinoctial element knots
// (3.5-day knots for Mimas and Enceladus), then solves Kepler at the requested instant.
// tools/validate_moons.py gates the result against Horizons vectors halfway between knots,
// so the checks are predictions rather than training-row lookups. Positions are for
// showing which side of its planet a moon is on and how the system is arranged — never for
// an occultation, a mutual event, or anything that has to be right to the arcminute.
//
// `col` and `note` are illustrative — JPL publishes GM, radius and density, never colour.

/** Reference epoch used for representative facts: JD 2461041.5 TDB. */
export const MOON_EPOCH_JD = 2461041.500000;
/** Every moon is independently validated throughout this exact interval. */
export const MOON_VALID_MIN_JD = 2459219.000000;
export const MOON_VALID_MAX_JD = 2462859.000000;

/** @typedef {{n:string,p:string,code:number,a:number,e:number,i:number,node:number,
 *  argp:number,M0:number,nd:number,P:number,r:number,rho:number|null,gm:number|null,
 *  col:[number,number,number],note:string,t0?:number,step?:number,el?:number[]}} Moon */

/** @type {Moon[]} */
export const MOONS = [
  {n:"Phobos",p:"Mars",code:401,a:9378.2,e:0.0152834,i:27.4174,node:81.08409,argp:160.69079,M0:10.34318,nd:1128.84484799,P:0.31891,r:11.1,rho:1.872,gm:0.0007087,col:[0.42,0.38,0.35],note:"Battered, grooved, and spiralling inward \u2014 it will break up in ~50 Myr."},
  {n:"Deimos",p:"Mars",code:402,a:23458.6,e:0.0002346,i:24.17296,node:81.22729,argp:27.05031,M0:312.15929,nd:285.16192707,P:1.262441,r:6.2,rho:1.471,gm:9.62e-05,col:[0.48,0.44,0.4],note:"The smaller, smoother, outer Martian moon."},
  {n:"Io",p:"Jupiter",code:501,a:422034.3,e:0.0045807,i:2.20653,node:338.48046,argp:240.75466,M0:111.84035,nd:203.48895823,P:1.769138,r:1821.5,rho:3.5276,gm:5959.91547,col:[0.94,0.84,0.42],note:"The most volcanically active world in the solar system \u2014 sulfur frosts, 400+ volcanoes."},
  {n:"Europa",p:"Jupiter",code:502,a:671235.1,e:0.009684,i:2.15029,node:325.93379,argp:77.91657,M0:234.02147,nd:101.37472568,P:3.551181,r:1560.8,rho:3.013,gm:3202.7121,col:[0.86,0.82,0.74],note:"A cracked ice shell over a global salt-water ocean holding twice Earth's water."},
  {n:"Ganymede",p:"Jupiter",code:503,a:1070486.8,e:0.0018087,i:2.33905,node:339.23136,argp:336.99855,M0:24.91393,nd:50.31759957,P:7.154554,r:2631.2,rho:1.9416,gm:9887.83275,col:[0.66,0.61,0.55],note:"Largest moon in the solar system \u2014 bigger than Mercury, and the only one with its own magnetic field."},
  {n:"Callisto",p:"Jupiter",code:504,a:1883458.7,e:0.00723,i:1.95167,node:336.70052,argp:36.13945,M0:76.01606,nd:21.57107991,P:16.689011,r:2410.3,rho:1.834,gm:7179.2834,col:[0.42,0.39,0.37],note:"The most heavily cratered object known; geologically dead for ~4 billion years."},
  {n:"Mimas",p:"Saturn",code:601,a:186011.8,e:0.0187596,i:29.62685,node:169.60794,argp:255.79427,M0:72.42789,nd:381.99493488,P:0.942421,r:198.2,rho:1.1501,gm:2.50349,col:[0.72,0.72,0.7],note:"Herschel crater spans a third of its diameter."},
  {n:"Enceladus",p:"Saturn",code:602,a:238409.7,e:0.0039701,i:28.05273,node:169.51478,argp:99.02925,M0:276.56604,nd:262.73176382,P:1.370219,r:252.1,rho:1.6097,gm:7.21037,col:[0.94,0.96,0.97],note:"Brightest surface in the solar system, venting water ice from a subsurface ocean."},
  {n:"Tethys",p:"Saturn",code:603,a:294974.7,e:0.0007458,i:27.20983,node:171.02671,argp:148.74761,M0:163.13531,nd:190.6978877,P:1.887803,r:531.1,rho:0.984,gm:41.21353,col:[0.8,0.8,0.78],note:"Almost pure water ice, scarred by the vast Ithaca Chasma."},
  {n:"Dione",p:"Saturn",code:604,a:377658.3,e:0.0024934,i:28.02455,node:169.52965,argp:242.58265,M0:175.84472,nd:131.53494148,P:2.736915,r:561.4,rho:1.4781,gm:73.11607,col:[0.76,0.76,0.74],note:"Wispy ice cliffs streak its trailing hemisphere."},
  {n:"Rhea",p:"Saturn",code:605,a:527229.2,e:0.0012312,i:28.24259,node:170.0343,argp:170.91974,M0:257.37599,nd:79.69002253,P:4.517504,r:763.5,rho:1.2372,gm:153.94175,col:[0.74,0.73,0.71],note:"Saturn's second largest \u2014 an ancient, cratered iceball."},
  {n:"Titan",p:"Saturn",code:606,a:1221979.1,e:0.02882,i:27.70896,node:169.07739,argp:177.99229,M0:352.26157,nd:22.57697026,P:15.945452,r:2574.8,rho:1.8814,gm:8978.1371,col:[0.86,0.66,0.34],note:"The only moon with a thick atmosphere, and the only other world with standing liquid \u2014 methane lakes."},
  {n:"Iapetus",p:"Saturn",code:608,a:3559866.9,e:0.0290085,i:16.99508,node:138.89496,argp:231.57167,M0:101.53789,nd:4.53792224,P:79.331461,r:734.3,rho:1.0887,gm:120.51511,col:[0.62,0.58,0.52],note:"Two-toned: one hemisphere as dark as coal, the other as bright as snow."},
  {n:"Ariel",p:"Uranus",code:701,a:190944.5,e:0.0006032,i:97.71524,node:167.66454,argp:243.1205,M0:273.72206,nd:142.8356284,P:2.52038,r:578.9,rho:1.539,gm:83.5,col:[0.76,0.77,0.78],note:"The brightest Uranian moon, resurfaced by past tectonics."},
  {n:"Umbriel",p:"Uranus",code:702,a:265986.0,e:0.0040873,i:97.71146,node:167.72418,argp:54.85527,M0:21.60694,nd:86.86889123,P:4.144176,r:584.7,rho:1.523,gm:85.1,col:[0.55,0.55,0.56],note:"The darkest of the five, with one puzzlingly bright ring-shaped feature."},
  {n:"Titania",p:"Uranus",code:703,a:436318.2,e:0.0025145,i:97.76331,node:167.64225,argp:264.20268,M0:306.00045,nd:41.3514213,P:8.705868,r:788.9,rho:1.653,gm:226.9,col:[0.72,0.7,0.68],note:"Largest Uranian moon, cut by enormous rift valleys."},
  {n:"Oberon",p:"Uranus",code:704,a:583517.3,e:0.0020109,i:97.90559,node:167.70976,argp:160.85643,M0:318.14259,nd:26.73948423,P:13.463236,r:761.4,rho:1.664,gm:205.3,col:[0.68,0.65,0.62],note:"The outermost large Uranian moon, its crater floors filled with dark material."},
  {n:"Miranda",p:"Uranus",code:705,a:129871.3,e:0.0016371,i:99.18483,node:163.42294,argp:49.08922,M0:103.30219,nd:254.69008899,P:1.413483,r:235.8,rho:1.178,gm:4.3,col:[0.7,0.71,0.72],note:"Cliffs up to 20 km high \u2014 the tallest known anywhere."},
  {n:"Triton",p:"Neptune",code:801,a:354765.0,e:0.000142,i:129.1483,node:222.66251,argp:107.88848,M0:301.75807,nd:61.25855176,P:5.876731,r:1352.6,rho:2.0649,gm:1428.49546,col:[0.84,0.8,0.8],note:"Orbits BACKWARDS \u2014 a captured Kuiper-belt object with nitrogen geysers and the coldest measured surface."},
  {n:"Nereid",p:"Neptune",code:802,a:5519145.7,e:0.7460546,i:5.04549,node:319.43528,argp:296.6795,M0:350.07547,nd:0.99972593,P:360.098694,r:170.0,rho:null,gm:null,col:[0.7,0.7,0.72],note:"One of the most eccentric orbits of any moon: 1.4 to 9.7 million km."},
  {n:"Proteus",p:"Neptune",code:808,a:117675.2,e:0.0006858,i:29.05919,node:48.7123,argp:14.52396,M0:66.37201,nd:320.76563941,P:1.122315,r:208.0,rho:1.0269,gm:2.58342,col:[0.52,0.52,0.53],note:"About as large as a body can get without gravity pulling it round."},
];

/** Moons of a given planet, innermost first. */
export function moonsOf(planet) {
  return MOONS.filter((m) => m.p === planet).sort((x, y) => x.a - y.a);
}

/** Planets that have at least one moon in this catalogue. */
export const MOON_PARENTS = [...new Set(MOONS.map((m) => m.p))];
