// GENERATED by tools/generate_moons.py — do not edit.
// @lazy-module: loaded on demand via dynamic import (orrery.js) when the 3-D view opens —
// must NOT be modulepreloaded or statically imported (validate_web_static enforces both).
//
// The 21 major moons (Jupiter 4, Mars 2, Neptune 3, Saturn 7, Uranus 5) — every satellite with a mean radius of at
// least 150 km, plus Mars's two. Osculating elements from JPL Horizons, PLANETOCENTRIC and
// already referred to the ecliptic J2000 plane, so they need no frame rotation: they are in
// the renderer's own frame. See tools/ephemeris-data/moons/README.md for why the elements
// come from Horizons rather than from JPL's satellite mean-elements table.
//
// ACCURACY — read this before trusting a position. Osculating elements describe the orbit
// a moon is on AT THE EPOCH; Kepler-propagating them ignores every perturbation that
// changes it afterwards, and satellite orbits are strongly perturbed. Measured against
// Horizons by tools/validate_moons.py, which gates the error in CI. Positions are for
// showing which side of its planet a moon is on and how the system is arranged — never for
// an occultation, a mutual event, or anything that has to be right to the arcminute.
//
// `col` and `note` are illustrative — JPL publishes GM, radius and density, never colour.

/** Epoch of every element set below: JD 2461041.5 TDB. */
export const MOON_EPOCH_JD = 2461041.500000;

/** @typedef {{n:string,p:string,code:number,a:number,e:number,i:number,node:number,
 *  argp:number,M0:number,nd:number,P:number,r:number,rho:number|null,gm:number|null,
 *  col:[number,number,number],note:string}} Moon */

/** @type {Moon[]} */
export const MOONS = [
  {n:"Phobos",p:"Mars",code:401,a:9378.4,e:0.0154878,i:27.41763,node:81.08381,argp:159.83266,M0:11.20346,nd:1128.84370294,P:0.31891,r:11.1,rho:1.872,gm:0.0007087,col:[0.42,0.38,0.35],note:"Battered, grooved, and spiralling inward \u2014 it will break up in ~50 Myr."},
  {n:"Deimos",p:"Mars",code:402,a:23458.8,e:0.0003461,i:24.17293,node:81.22755,argp:28.03163,M0:311.16546,nd:285.16183439,P:1.262441,r:6.2,rho:1.471,gm:9.62e-05,col:[0.48,0.44,0.4],note:"The smaller, smoother, outer Martian moon."},
  {n:"Io",p:"Jupiter",code:501,a:422029.0,e:0.0039879,i:2.20652,node:338.4807,argp:255.08139,M0:97.50893,nd:203.48931134,P:1.769135,r:1821.5,rho:3.5276,gm:5959.91547,col:[0.94,0.84,0.42],note:"The most volcanically active world in the solar system \u2014 sulfur frosts, 400+ volcanoes."},
  {n:"Europa",p:"Jupiter",code:502,a:671309.9,e:0.0092862,i:2.15043,node:325.93533,argp:76.30383,M0:235.64243,nd:101.37543721,P:3.551156,r:1560.8,rho:3.013,gm:3202.7121,col:[0.86,0.82,0.74],note:"A cracked ice shell over a global salt-water ocean holding twice Earth's water."},
  {n:"Ganymede",p:"Jupiter",code:503,a:1070853.6,e:0.0021858,i:2.33905,node:339.23055,argp:338.52502,M0:23.37772,nd:50.31749782,P:7.154569,r:2631.2,rho:1.9416,gm:9887.83275,col:[0.66,0.61,0.55],note:"Largest moon in the solar system \u2014 bigger than Mercury, and the only one with its own magnetic field."},
  {n:"Callisto",p:"Jupiter",code:504,a:1882639.6,e:0.0073467,i:1.95162,node:336.70284,argp:33.21224,M0:78.92851,nd:21.57108098,P:16.689011,r:2410.3,rho:1.834,gm:7179.2834,col:[0.42,0.39,0.37],note:"The most heavily cratered object known; geologically dead for ~4 billion years."},
  {n:"Mimas",p:"Saturn",code:601,a:186022.6,e:0.0204012,i:29.62763,node:169.60496,argp:258.27081,M0:69.9584,nd:381.9976529,P:0.942414,r:198.2,rho:1.1501,gm:2.50349,col:[0.72,0.72,0.7],note:"Herschel crater spans a third of its diameter."},
  {n:"Enceladus",p:"Saturn",code:602,a:238411.4,e:0.0050434,i:28.05272,node:169.51476,argp:82.52459,M0:293.06771,nd:262.73109905,P:1.370222,r:252.1,rho:1.6097,gm:7.21037,col:[0.94,0.96,0.97],note:"Brightest surface in the solar system, venting water ice from a subsurface ocean."},
  {n:"Tethys",p:"Saturn",code:603,a:294975.1,e:0.001117,i:27.20982,node:171.02724,argp:316.64989,M0:355.23057,nd:190.69803948,P:1.887801,r:531.1,rho:0.984,gm:41.21353,col:[0.8,0.8,0.78],note:"Almost pure water ice, scarred by the vast Ithaca Chasma."},
  {n:"Dione",p:"Saturn",code:604,a:377653.5,e:0.0016399,i:28.02456,node:169.52958,argp:256.91167,M0:161.52029,nd:131.53513873,P:2.736911,r:561.4,rho:1.4781,gm:73.11607,col:[0.76,0.76,0.74],note:"Wispy ice cliffs streak its trailing hemisphere."},
  {n:"Rhea",p:"Saturn",code:605,a:527213.7,e:0.0008829,i:28.24261,node:170.03447,argp:157.31403,M0:270.97124,nd:79.69006882,P:4.517501,r:763.5,rho:1.2372,gm:153.94175,col:[0.74,0.73,0.71],note:"Saturn's second largest \u2014 an ancient, cratered iceball."},
  {n:"Titan",p:"Saturn",code:606,a:1221941.3,e:0.028812,i:27.70896,node:169.0774,argp:177.9434,M0:352.31052,nd:22.57694385,P:15.945471,r:2574.8,rho:1.8814,gm:8978.1371,col:[0.86,0.66,0.34],note:"The only moon with a thick atmosphere, and the only other world with standing liquid \u2014 methane lakes."},
  {n:"Iapetus",p:"Saturn",code:608,a:3558935.3,e:0.0290538,i:16.99531,node:138.89588,argp:231.02267,M0:102.08703,nd:4.5379978,P:79.33014,r:734.3,rho:1.0887,gm:120.51511,col:[0.62,0.58,0.52],note:"Two-toned: one hemisphere as dark as coal, the other as bright as snow."},
  {n:"Ariel",p:"Uranus",code:701,a:190940.7,e:0.0006105,i:97.71522,node:167.66454,argp:228.23928,M0:288.60036,nd:142.83547844,P:2.520382,r:578.9,rho:1.539,gm:83.5,col:[0.76,0.77,0.78],note:"The brightest Uranian moon, resurfaced by past tectonics."},
  {n:"Umbriel",p:"Uranus",code:702,a:266006.0,e:0.0041519,i:97.71147,node:167.72417,argp:55.23268,M0:21.23248,nd:86.86903505,P:4.144169,r:584.7,rho:1.523,gm:85.1,col:[0.55,0.55,0.56],note:"The darkest of the five, with one puzzlingly bright ring-shaped feature."},
  {n:"Titania",p:"Uranus",code:703,a:436267.5,e:0.0024592,i:97.76331,node:167.64225,argp:261.89143,M0:308.30426,nd:41.35146233,P:8.705859,r:788.9,rho:1.653,gm:226.9,col:[0.72,0.7,0.68],note:"Largest Uranian moon, cut by enormous rift valleys."},
  {n:"Oberon",p:"Uranus",code:704,a:583607.4,e:0.0021005,i:97.90559,node:167.70976,argp:156.6162,M0:322.38554,nd:26.73942852,P:13.463265,r:761.4,rho:1.664,gm:205.3,col:[0.68,0.65,0.62],note:"The outermost large Uranian moon, its crater floors filled with dark material."},
  {n:"Miranda",p:"Uranus",code:705,a:129879.2,e:0.0013306,i:99.18608,node:163.42299,argp:55.85907,M0:96.53505,nd:254.6932941,P:1.413465,r:235.8,rho:1.178,gm:4.3,col:[0.7,0.71,0.72],note:"Cliffs up to 20 km high \u2014 the tallest known anywhere."},
  {n:"Triton",p:"Neptune",code:801,a:354766.2,e:0.0001383,i:129.14813,node:222.66204,argp:102.17055,M0:307.47587,nd:61.2573817,P:5.876843,r:1352.6,rho:2.0649,gm:1428.49546,col:[0.84,0.8,0.8],note:"Orbits BACKWARDS \u2014 a captured Kuiper-belt object with nitrogen geysers and the coldest measured surface."},
  {n:"Nereid",p:"Neptune",code:802,a:5509318.3,e:0.7456081,i:5.03372,node:319.29813,argp:296.83568,M0:350.04895,nd:0.99966248,P:360.121548,r:170.0,rho:null,gm:null,col:[0.7,0.7,0.72],note:"One of the most eccentric orbits of any moon: 1.4 to 9.7 million km."},
  {n:"Proteus",p:"Neptune",code:808,a:117674.0,e:0.0005789,i:29.05946,node:48.71128,argp:28.68417,M0:52.21291,nd:320.76572932,P:1.122314,r:208.0,rho:1.0269,gm:2.58342,col:[0.52,0.52,0.53],note:"About as large as a body can get without gravity pulling it round."},
];

/** Moons of a given planet, innermost first. */
export function moonsOf(planet) {
  return MOONS.filter((m) => m.p === planet).sort((x, y) => x.a - y.a);
}

/** Planets that have at least one moon in this catalogue. */
export const MOON_PARENTS = [...new Set(MOONS.map((m) => m.p))];
