// Generated by tools/extract_sun_look.py from the approved standalone v2.
// Source SHA-256: 7cc33aae070dd48ad26efdd166be91c8e6b75d59b085399e7d9a693610e33a18
// Illustrative appearance only; no observation or physical field is inferred.
export const LAB_SCENE_FS = `#version 300 es
precision highp float;
out vec4 o;
uniform vec2 u_res;uniform float u_scale,u_rot,u_tilt,u_radiusPx;
uniform float u_net,u_dark,u_fans,u_corona,u_prom,u_detail,u_wisps;
uniform int u_pal,u_direct;
uniform vec4 u_ar[10];  // lat, lon, separation (rad), axis tilt (rad)
uniform float u_arAmp[10];

const float PI=3.14159265;
vec3 ghash(vec3 p){p=vec3(dot(p,vec3(127.1,311.7,74.7)),dot(p,vec3(269.5,183.3,246.1)),dot(p,vec3(113.5,271.9,124.6)));return -1.+2.*fract(sin(p)*43758.5453123);}
float hash1(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,37.719)))*43758.5453);}
uniform float u_flow;
// Flow noise: lattice gradients rotate over time, so the field evolves in place.
vec3 grad(vec3 c){vec3 g=ghash(c);float a=u_flow*(.6+.8*hash1(c+3.1));float s=sin(a),k=cos(a);return vec3(k*g.x-s*g.y,s*g.x+k*g.y,g.z);}
float gnoise(vec3 p){
  vec3 i=floor(p),f=fract(p),u=f*f*f*(f*(f*6.-15.)+10.);
  float a=dot(grad(i),f),b=dot(grad(i+vec3(1,0,0)),f-vec3(1,0,0)),c=dot(grad(i+vec3(0,1,0)),f-vec3(0,1,0)),d=dot(grad(i+vec3(1,1,0)),f-vec3(1,1,0));
  float e=dot(grad(i+vec3(0,0,1)),f-vec3(0,0,1)),g=dot(grad(i+vec3(1,0,1)),f-vec3(1,0,1)),h=dot(grad(i+vec3(0,1,1)),f-vec3(0,1,1)),j=dot(grad(i+vec3(1,1,1)),f-vec3(1,1,1));
  return mix(mix(mix(a,b,u.x),mix(c,d,u.x),u.y),mix(mix(e,g,u.x),mix(h,j,u.x),u.y),u.z);
}
float fbm(vec3 p,int oct){float s=0.,a=.5;for(int i=0;i<6;i++){if(i>=oct)break;s+=a*gnoise(p);p=p*2.03+vec3(1.7,-.3,.9);a*=.5;}return s;}
float ridged(vec3 p,int oct){float s=0.,a=.5;for(int i=0;i<5;i++){if(i>=oct)break;float r=1.-abs(gnoise(p));s+=a*r*r;p=p*2.11+vec3(-.7,.4,1.3);a*=.55;}return s;}
uniform float u_time;
vec2 worley(vec3 p){
  vec3 i=floor(p),f=fract(p);float d1=8.,d2=8.;
  for(int z=-1;z<=1;z++)for(int y=-1;y<=1;y++)for(int x=-1;x<=1;x++){
    vec3 o=vec3(x,y,z),h=.5+.5*ghash(i+o);
    h=.5+.42*sin(u_time*.09+6.2831*h); // sites orbit their seeds: cells reshape, never slide
    vec3 r=o+h-f;float d=dot(r,r);
    if(d<d1){d2=d1;d1=d;}else if(d<d2)d2=d;
  }
  return sqrt(vec2(d1,d2));
}

vec3 palette(float I,int pal){
  I=max(I,0.);
  if(pal==0)return vec3(1.-exp(-2.3*I),1.-exp(-.68*pow(I,1.4)),1.-exp(-.1*pow(I,2.4)));
  return vec3(1.-exp(-.85*I),1.-exp(-.58*pow(I,1.25)),1.-exp(-.13*pow(I,2.1)));
}
vec3 promColor(int pal){return pal==0?vec3(1.,.28,.05):vec3(.95,.62,.16);}
mat3 bodyFromWorld(){
  float c=cos(u_rot),s=sin(u_rot),ct=cos(u_tilt),st=sin(u_tilt);
  mat3 ry=mat3(c,0.,-s, 0.,1.,0., s,0.,c);      // spin about north (+y)
  mat3 rx=mat3(1.,0.,0., 0.,ct,st, 0.,-st,ct);  // B0 tilt toward the viewer
  return ry*rx;
}
vec3 sph(float lat,float lon){return vec3(cos(lat)*sin(lon),sin(lat),cos(lat)*cos(lon));}
float fanField(vec3 p,vec4 ar,float amp,out float core,out float plage){
  vec3 c=sph(ar.x,ar.y);core=0.;plage=0.;
  float cd=dot(p,c);if(cd<.55)return 0.;
  vec3 east=normalize(cross(vec3(0,1,0),c)),north=cross(c,east);
  float ct=cos(ar.w),st=sin(ar.w);vec3 a=ct*east+st*north,b=cross(c,a);
  vec3 q=p-c*cd;float x=dot(q,a),y=dot(q,b),d=ar.z;
  float r1=length(vec2(x-.5*d,y)),r2=length(vec2(x+.5*d,y)),rm=length(vec2(x,y));
  // Angle the two poles subtend: its contours are the arcs of a line dipole.
  float psi=atan(y,x-.5*d)-atan(y,x+.5*d);
  psi+=.22*gnoise(vec3(x,y,ar.y)*38.)+.08*gnoise(vec3(x,y,ar.x)*110.); // bends and frays the arcs
  float n=psi*9./PI,f=fract(n),id=floor(n);
  float w=.11+.10*smoothstep(0.,d*2.,rm);
  float line=exp(-pow(min(f,1.-f)/w,2.));
  float strand=(.35+1.3*pow(hash1(vec3(id,ar.x,ar.y)),2.))*(.75+.25*sin(u_time*(.3+hash1(vec3(id,1.,ar.y)))+id));
  // Finer secondary strands between the main arcs.
  float n2=psi*23./PI,f2=fract(n2);float fine=.35*exp(-pow(min(f2,1.-f2)/.14,2.))*(.5+hash1(vec3(floor(n2),ar.y,2.)));
  float env=exp(-min(r1,r2)/(d*.75))*(1.-smoothstep(d*1.4,d*3.2,rm));
  float s=d*.09*(1.+.5*gnoise(vec3(x,y,1.)*80.));float ex=(1.+.8*abs(gnoise(vec3(x,y,2.)*40.)));
  core=(exp(-(r1*r1)/(s*s*ex))+.7*exp(-(r2*r2)/(s*s*ex)))*amp;
  plage=exp(-rm*rm/(d*d*1.1))*amp;
  return (line*strand+fine)*env*amp;
}
void main(){
  vec2 uv=(gl_FragCoord.xy-.5*u_res)/(.5*u_res.y);
  vec2 q=uv*u_scale;float b=length(q);
  float px=u_radiusPx;                       // disk radius in device pixels
  float dNet=smoothstep(22.,70.,px),dFine=smoothstep(70.,220.,px),dFan=smoothstep(28.,90.,px);
  mat3 B=bodyFromWorld();
  float I=0.,P=0.;
  if(b<1.){
    vec3 nw=vec3(q,sqrt(1.-b*b));float mu=nw.z;
    vec3 p=B*nw;
    // Analytic footprint remains defined at the sphere branch and limb.
    float footprint=1./(max(px,1.)*max(mu,.06));
    float cellLOD=1.-smoothstep(.18,.55,footprint*74.);
    float fineLOD=1.-smoothstep(.18,.60,footprint*155.);
    float microLOD=1.-smoothstep(.18,.60,footprint*310.);
    // Quiet corona: mottling, a warped network with bright points, and flame-like filaments.
    float mott=fbm(p*5.,4);
    vec3 warp=vec3(gnoise(p*9.),gnoise(p*9.+5.),gnoise(p*9.+11.));
    vec2 w=worley(p*16.+.9*warp);
    float lanes=1.-smoothstep(0.,.22,w.y-w.x);
    float bp=pow(max(0.,1.-w.x*2.6),6.)*smoothstep(0.,.3,gnoise(p*4.+7.));
    float flame=ridged(p*26.+1.6*warp,4);
    float quiet=.30+.24*mott;
    quiet+=u_net*(dNet*(.10*lanes*(.6+.8*gnoise(p*12.))+1.2*bp)+dFine*.62*(flame-.34));
    float cellTexture=0.,fineTexture=0.,microTexture=0.;
    if(u_detail>0. && u_net>0.){
      if(cellLOD>0.){
        vec2 cells=worley(p*74.+warp*1.7);
        float aa=max(.018,footprint*74.*.6);
        float threads=1.-smoothstep(.035-aa,.13+aa,cells.y-cells.x);
        float grain=pow(max(0.,1.-cells.x*1.8),3.);
        cellTexture=cellLOD*(.11*(threads-.36)+.30*grain);
      }
      if(fineLOD>0.)fineTexture=fineLOD*.11*(ridged(p*155.+warp*3.,2)-.75);
      if(microLOD>0.)microTexture=microLOD*.07*gnoise(p*310.+warp*4.);
    }
    quiet+=u_net*u_detail*(cellTexture+fineTexture+microTexture);
    quiet=max(quiet,.015);quiet=1.15*pow(quiet,1.25);
    // Dark regions: warped threshold, torn at two finer scales, network kept inside.
    vec3 wp=p*1.25+.55*vec3(fbm(p*1.6,3),fbm(p*1.6+4.,3),fbm(p*1.6+9.,3));
    float m=fbm(wp,4)+.34*fbm(p*6.+warp,3)+.18*dFine*fbm(p*18.,2);
    // Edge shredding preserves the large dark regions and their inner texture.
    m+=u_detail*cellLOD*.025*gnoise(p*74.+warp);
    float hole=smoothstep(-.01,.12,m)*u_dark;
    I=quiet*mix(1.,.30+.12*fbm(p*14.,2)+u_detail*cellLOD*.035*gnoise(p*94.+warp),hole);
    // Active regions.
    for(int i=0;i<10;i++){
      float core,plage;float fan=fanField(p,u_ar[i],u_arAmp[i],core,plage);
      I+=u_fans*(dFan*3.0*fan+.55*plage*(.6+.8*mott)+2.8*core);
    }
    // Optically thin limb brightening plus an emissive rim.
    I*=1.+.55*pow(1.-mu,2.);
    I+=u_corona*1.1*exp(-mu*14.);
  }else{
    float h=b-1.;vec2 dir=q/b;float ang=atan(dir.y,dir.x);
    if(u_corona>0.){
      // Periodic coordinates avoid a polar seam. Height-dependent curls
      // break straight rays into short, curved, diffuse sheets.
      float curl=fbm(vec3(dir*4.,h*5.-u_time*.045),3);
      float bend=(.10*sin(ang*7.+h*14.-u_time*.06)+.16*curl)*smoothstep(0.,.12,h);
      float a=ang+bend;
      vec3 wq=vec3(cos(a)*42.,sin(a)*42.,h*28.-u_time*.09);
      float sheet=pow(max(0.,1.-abs(gnoise(wq))),2.2);
      float veil=.5+.5*gnoise(vec3(cos(a)*15.,sin(a)*15.,h*22.+u_time*.035));
      float fray=.55+.45*gnoise(wq*1.8+vec3(0.,0.,h*18.));
      float fade=1.-smoothstep(.10,.32,h);
      float feather=sheet*veil*fray*exp(-h/.095)*fade;
      float cor=1.7*exp(-h/.018)+.23*exp(-h/.080)+.07*exp(-h/.20);
      cor+=u_wisps*(1.15*feather+.09*veil*exp(-h/.15)*fade);
      // Loop arcs above the limb where an active region sits near it.
      for(int i=0;i<10;i++){
        vec3 cw=transpose(B)*sph(u_ar[i].x,u_ar[i].y);
        float near=(1.-smoothstep(.05,.6,abs(cw.z)));
        if(near<=0.)continue;
        vec2 foot=normalize(cw.xy+1e-5),tang=vec2(-foot.y,foot.x);float r=length(q-foot);
        float span=u_ar[i].z;float arcs=0.;
        for(int k=0;k<7;k++){
          float hk=hash1(vec3(float(i),float(k),3.)),jk=hash1(vec3(float(k),float(i),5.))-.5;
          vec2 ck=normalize(foot+tang*jk*span*1.4);
          float rk=span*(.22+.55*hk),e=abs(length(q-ck)-rk+.004*gnoise(vec3(q*90.,float(k))));
          arcs+=(.3+hash1(vec3(float(k),float(i),9.)))*exp(-pow(e/(.004+.003*hk),2.))*(1.-smoothstep(rk*.2,rk*1.05,length(q-ck)));
        }
        cor+=near*u_arAmp[i]*(1.5*arcs*dFan*smoothstep(0.,.012,h)+.8*exp(-r/.07));
      }
      I+=u_corona*cor;
    }
    if(u_prom>0.){
      // Optional evolving geometry, strands and brightness. Artistic, not MHD.
      // Continuous cycles avoid resets and popping.
      for(int k=0;k<3;k++){
        float seed=float(k)*2.1,phase=u_time*.20+seed;
        float growth=.5+.5*sin(phase);
        float pa=(k==0?2.3:(k==1?-2.55:-.5))+.04*sin(phase*.8);
        vec2 foot=vec2(cos(pa),sin(pa)),tangent=vec2(-foot.y,foot.x);
        float width=(k==0?.19:.085)*(.85+.15*sin(phase*.7));
        float height=(k==0?.22:.11)*(.50+.65*growth);
        vec2 delta=q-foot;
        float x=dot(delta,tangent),y=dot(delta,foot);
        float lean=.18*sin(phase*.8),ax=x-lean*y;
        float along=clamp(ax/width,-1.,1.);
        float arch=height*sqrt(max(0.,1.-along*along));
        float env=(1.-smoothstep(width*.86,width*1.07,abs(ax)))*smoothstep(0.,.018,h);
        float turb=fbm(vec3(ax*45.,y*32.,u_time*.13+seed),3);
        float band=0.;
        for(int j=0;j<5;j++){
          float strand=float(j)-2.;
          float drift=.008*sin(along*9.+phase*1.7+strand);
          float ridge=arch*(1.+strand*.04)+drift+.022*turb;
          float e=(y-ridge)/(.005+.004*abs(turb));
          float flow=.55+.45*sin(along*14.-u_time*.9+strand*1.6);
          band+=exp(-e*e)*flow;
        }
        P+=band*env*(.25+.75*growth)*(.55+.7*max(turb,0.));
      }
      P*=u_prom;
    }
  }
  if(u_direct==1){o=vec4(palette(I,u_pal)+promColor(u_pal)*(1.-exp(-P*1.3)),1.);return;}
  o=vec4(I,P,0.,1.);
}`;
export const LAB_BLUR_FS = `#version 300 es
precision highp float;
out vec4 o;uniform sampler2D u_src;uniform vec2 u_dir,u_texel;uniform float u_threshold;
void main(){
  vec2 uv=gl_FragCoord.xy*u_texel;vec4 s=vec4(0.);float wsum=0.;
  for(int i=-6;i<=6;i++){float w=exp(-float(i*i)/18.);vec4 v=texture(u_src,uv+u_dir*float(i)*2.);
    s+=w*vec4(max(v.r-u_threshold,0.),v.g,0.,0.);wsum+=w;}
  o=s/wsum;
}`;
