#!/usr/bin/env python3
"""Extract the owner-approved Sun v2 shaders without its page or reference images."""
import argparse
import hashlib
from pathlib import Path
import re

APPROVED_SHA256 = '7cc33aae070dd48ad26efdd166be91c8e6b75d59b085399e7d9a693610e33a18'
ROOT = Path(__file__).resolve().parents[1]

def extract(source: Path) -> str:
    data = source.read_bytes()
    if hashlib.sha256(data).hexdigest() != APPROVED_SHA256:
        raise ValueError('Source does not match the approved Sun Surface Lab v2')
    text = data.decode('utf-8')
    parts = {}
    for name in ('COMMON', 'SCENE_FS', 'BLUR_FS'):
        found = re.search(r'const '+name+r'=`(.*?)`;', text, re.S)
        if not found:
            raise ValueError('Missing shader '+name)
        parts[name] = found.group(1)
    parts['SCENE_FS'] = parts['SCENE_FS'].replace('${COMMON}', parts['COMMON'])
    return ('// Generated by tools/extract_sun_look.py from the approved standalone v2.\n'
            '// Source SHA-256: '+APPROVED_SHA256+'\n'
            '// Illustrative appearance only; no observation or physical field is inferred.\n'
            + ''.join('export const LAB_'+name+' = `'+parts[name]+'`;\n' for name in ('SCENE_FS','BLUR_FS')))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'tools/lookdev/sun-surface-lab-v2.html')
    args = parser.parse_args()
    output = ROOT / 'apps/web/js/sunLookRecipe.js'
    output.write_text(extract(args.source), encoding='utf-8', newline='\n')
    print(output)
