#!/usr/bin/env python3
"""Offline, conservative offshore display mask; never a scientific ocean product.

Uses committed public-domain Natural Earth 1:110m land and glaciated-area rings.
Interior holes remain protected (inland water is not an ocean). A two-pixel
offshore margin and the shader's dark-blue gate protect the coarse coastline.
Run with --check to verify deterministic regeneration.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tools/ephemeris-data/geography"
OUTPUT = ROOT / "apps/web/js/earthOceanMask.js"
WIDTH, HEIGHT = 512, 256
INPUTS = {
    "ne_110m_land.geojson": "9e0729ee253ca7d7a5c4ae9395fb1902264c5377c52e224d13dd85010e2835d9",
    "ne_110m_glaciated_areas.geojson": "e61e3f45e22f087f861ac2fda6258fc15c849a216d74c27ccf0164eeafbd950a",
}


def unwrapped(ring):
    lon = (ring[0][0] + 180) % 360 - 180
    points = [((lon + 180) * WIDTH / 360, (90 - ring[0][1]) * HEIGHT / 180)]
    for a, b in zip(ring, ring[1:]):
        delta = b[0] - a[0]
        if delta > 180:
            delta -= 360
        elif delta < -180:
            delta += 360
        lon += delta
        points.append(((lon + 180) * WIDTH / 360, (90 - b[1]) * HEIGHT / 180))
    return points


def mask_pixels():
    # Integer bit rows keep rasterization/dilation deterministic without image libraries.
    rows = [0] * HEIGHT
    for name, digest in INPUTS.items():
        data = (SOURCE / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError(f"Source hash mismatch: {name}")
        for feature in json.loads(data)["features"]:
            geometry = feature["geometry"]
            polygons = [geometry["coordinates"]] if geometry["type"] == "Polygon" else geometry["coordinates"]
            for polygon in polygons:
                ring = polygon[0]
                points = unwrapped(ring)
                if abs(points[-1][0] - points[0][0]) > WIDTH * .99:
                    # Close polar rings at their westernmost vertex, through the pole.
                    start = min(range(len(points) - 1), key=lambda i: points[i][0])
                    ring = ring[start:-1] + ring[:start] + [ring[start]]
                    points = unwrapped(ring)
                    pole = HEIGHT if sum(p[1] for p in ring) < 0 else 0
                    points += [(points[-1][0], pole), (points[0][0], pole)]
                for offset in (-WIDTH, 0, WIDTH):
                    shifted = [(x + offset, y) for x, y in points]
                    edges = list(zip(shifted, shifted[1:] + shifted[:1]))
                    for y in range(max(0, math.floor(min(p[1] for p in shifted))),
                                   min(HEIGHT, math.ceil(max(p[1] for p in shifted)))):
                        scan = y + .5
                        hits = sorted(a[0] + (scan - a[1]) * (b[0] - a[0]) / (b[1] - a[1])
                                      for a, b in edges if (a[1] > scan) != (b[1] > scan))
                        for left, right in zip(hits[::2], hits[1::2]):
                            lo, hi = max(0, math.ceil(left - .5)), min(WIDTH, math.ceil(right - .5))
                            if hi > lo:
                                rows[y] |= ((1 << (hi - lo)) - 1) << lo
    # Two-pixel dilation, wrapping longitude and clamping the poles.
    full = (1 << WIDTH) - 1
    protected = []
    for y in range(HEIGHT):
        row = 0
        for source in rows[max(0, y - 2):min(HEIGHT, y + 3)]:
            row |= source
        expanded = row
        for shift in (1, 2):
            expanded |= ((row << shift) | (row >> (WIDTH - shift))) & full
            expanded |= ((row >> shift) | (row << (WIDTH - shift))) & full
        protected.extend(0 if expanded & (1 << x) else 255 for x in range(WIDTH))
    return bytes(protected)


def generate():
    pixels = mask_pixels()
    runs, previous, length = [], 0, 0
    for value in pixels:
        if value != previous:
            runs.append(length)
            previous, length = value, 0
        length += 1
    runs.append(length)
    return (
        "// GENERATED by tools/prepare_earth_ocean_mask.py. Public-domain Natural Earth.\n"
        "// Conservative offshore display mask, not a qualified coastline or reflectance map.\n"
        f"export const OCEAN_MASK_WIDTH={WIDTH},OCEAN_MASK_HEIGHT={HEIGHT};\n"
        f"export const OCEAN_MASK_SOURCES={json.dumps(INPUTS, separators=(',', ':'))};\n"
        f"export const OCEAN_MASK_SHA256='{hashlib.sha256(pixels).hexdigest()}';\n"
        f"export const OCEAN_MASK_RUNS={json.dumps(runs, separators=(',', ':'))};\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit("Earth ocean mask differs; regenerate it")
        print("OK: Earth ocean mask reproduces exactly")
    else:
        OUTPUT.write_text(content)
        print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(content)} bytes)")
