"""Bind existing immutable solar appearance products to their browser index."""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path


def prepare(web_root: Path) -> dict[str, dict[str, object]]:
    records: dict[str, dict[str, object]] = {}
    for name in ("quiet-v1", "active-v1"):
        relative = f"solar-dynamic/{name}/manifest.json"
        data = (web_root / relative).read_bytes()
        value = json.loads(data)
        if value.get("schema_version") != "solar-dynamic-appearance.v1" or value.get("id") != name:
            raise ValueError("Solar appearance manifest identity mismatch")
        records[name] = {"path": relative, "bytes": len(data), "sha256": hashlib.sha256(data).hexdigest()}
    output = "// Generated by tools/prepare_solar_dynamic_index.py; immutable product identities.\n"
    output += "export const solarDynamicBundles = Object.freeze(" + json.dumps(records, separators=(",", ":")) + ");\n"
    (web_root / "js" / "solarDynamicManifest.js").write_text(output, encoding="utf-8", newline="\n")
    return records


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--web-root", type=Path, default=Path("apps/web"))
    args = parser.parse_args()
    print(json.dumps(prepare(args.web_root), indent=2))
