// Explicit offline preparation. Builds never regenerate optical data.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {generateAtmosphereColumns} from '../apps/web/js/atmosphereColumnField.js';
import {getAtmosphereProfile,serializeAtmosphereProfile,ATMOSPHERE_PROFILE_ENCODING} from '../apps/web/js/atmosphereOptics.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),hash=b=>createHash('sha256').update(b).digest('hex');
const normalized=relative=>fs.readFileSync(path.join(root,relative),'utf8').replace(/\r\n/g,'\n');
const records={};
for(const body of ['Earth','Mars']){
  const profile=getAtmosphereProfile(body),values=generateAtmosphereColumns(profile),bytes=Buffer.alloc(values.byteLength);
  for(let i=0;i<values.length;i++)bytes.writeFloatLE(values[i],i*4);
  const name=`${body.toLowerCase()}-columns-v1.f32`,destination=path.join(root,'apps/web/data/optics',name);
  fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,bytes);
  records[body]={path:`../data/optics/${name}`,dimensions:[512,512,2],bytes:bytes.length,sha256:hash(bytes),
    format:'little-endian-rg32f-outward-columns-v1',profile_encoding:ATMOSPHERE_PROFILE_ENCODING,profile_sha256:hash(serializeAtmosphereProfile(profile)),
    generator_source_sha256:hash(normalized('tools/prepare_atmosphere_columns.mjs')),
    field_source_sha256:hash(normalized('apps/web/js/atmosphereColumnField.js')),
    solver_source_sha256:hash(normalized('apps/web/js/atmosphereShaders.js')),
    profile_source_sha256:hash(normalized('apps/web/js/atmosphereOptics.js'))};
}
fs.writeFileSync(path.join(root,'apps/web/js/atmosphereColumnManifest.js'),'// Generated by tools/prepare_atmosphere_columns.mjs. Numerical density columns, not imagery.\nexport const ATMOSPHERE_COLUMN_FIELDS=Object.freeze('+JSON.stringify(records,null,2)+');\n');
console.log(JSON.stringify({status:'prepared',bodies:Object.keys(records),bytes:Object.values(records).reduce((n,r)=>n+r.bytes,0)}));
