// Real depth-attached WebGL regression for the production solar transfer shader.
// A photosphere point x=1 maps to depth .8. A foreground strand x=1.2..1.3
// must add .1 emission at a smaller depth; an early return with unwritten
// gl_FragDepth previously caused the strand to disappear without a GL error.
import http from 'node:http';import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import puppeteer from 'puppeteer-core';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {mkdir} from 'node:fs/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const output=path.resolve(process.argv.find(x=>x.startsWith('--out='))?.slice(6)||path.join(root,'build/solar-depth-gpu-validation.json'));const server=http.createServer(async(req,res)=>{try{const requested=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!requested.startsWith(root+path.sep))throw Error('outside root');res.setHeader('Content-Type','text/javascript');res.end(await readFile(requested));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await puppeteer.launch({...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{channel:'chrome'}),headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-gl=angle']});const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/package.json`);const result=await page.evaluate(async()=>{
const {DYNAMIC_SOLAR_FS}=await import('/apps/web/js/solarAtmosphereShaders.js');const {SOLAR_STRAND_FS}=await import('/apps/web/js/solarStrandShaders.js');const gl=document.createElement('canvas').getContext('webgl2');gl.getExtension('EXT_color_buffer_float');
function texture(internal,format,type){const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,internal,1,1,0,format,type,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);return t;}
const color=texture(gl.RGBA32F,gl.RGBA,gl.FLOAT),depth=texture(gl.DEPTH_COMPONENT24,gl.DEPTH_COMPONENT,gl.UNSIGNED_INT);const fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,color,0);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.TEXTURE_2D,depth,0);gl.viewport(0,0,1,1);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);
const prefix='#version 300 es\nprecision highp float;\n',tri='gl_Position=vec4(gl_VertexID==1?3.:-1.,gl_VertexID==2?3.:-1.,0.,1.);';
function prog(vs,fs){const p=gl.createProgram();for(const [type,source]of[[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const loc=(p,n)=>gl.getUniformLocation(p,n),i=(p,n,v)=>gl.uniform1i(loc(p,n),v),f=(p,n,v)=>gl.uniform1f(loc(p,n),v);const matrix=new Float32Array([1,0,-.2,0,0,1,0,0,0,0,1,0,0,0,.8,1]);
const volume=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_3D,volume);gl.texImage3D(gl.TEXTURE_3D,0,gl.R32F,1,1,1,0,gl.RED,gl.FLOAT,new Float32Array([0]));gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
const vs=prefix+'out vec3 v_obj;void main(){v_obj=vec3(0);'+tri+'}';
const str=prog(prefix+'out vec3 v_plane;flat out vec4 v_start,v_end,v_pulse,v_arc;void main(){v_plane=vec3(0);v_start=vec4(1.2,0,0,.02);v_end=vec4(1.3,0,0,1);v_pulse=vec4(0);v_arc=vec4(0,1,1,0);'+tri+'}',SOLAR_STRAND_FS);
function pixel(){const a=new Float32Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.FLOAT,a);return [...a];}
const debugRenderer=gl.getExtension('WEBGL_debug_renderer_info');const renderer=gl.getParameter(debugRenderer?debugRenderer.UNMASKED_RENDERER_WEBGL:gl.RENDERER);const results={renderer};for(const [name,fs]of[['original',DYNAMIC_SOLAR_FS],['depth_initialized_control',DYNAMIC_SOLAR_FS.replace('void main(){','void main(){gl_FragDepth=.8;')]]){
const p=prog(vs,fs);gl.useProgram(p);gl.clearBufferfv(gl.COLOR,0,new Float32Array(4));gl.depthMask(true);gl.clearBufferfv(gl.DEPTH,0,new Float32Array([1]));gl.disable(gl.BLEND);i(p,'u_debug',1);i(p,'u_pass',1);i(p,'u_channel',1);i(p,'u_volume',0);i(p,'u_pulse',0);i(p,'u_surface',1);f(p,'u_extent',2.5);gl.uniform3f(loc(p,'u_camObj'),5,0,0);gl.uniform4f(loc(p,'u_surfaceRecipe'),5772,.6,1000,0);gl.uniformMatrix4fv(loc(p,'u_mvp'),false,matrix);gl.drawArrays(gl.TRIANGLES,0,3);const before=pixel();
gl.useProgram(str);gl.uniform3f(loc(str,'u_camera'),5,0,0);i(str,'u_transfer',1);gl.uniformMatrix4fv(loc(str,'u_mvp'),false,matrix);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE);gl.depthMask(false);gl.drawArrays(gl.TRIANGLES,0,3);results[name]={before,after:pixel(),error:gl.getError()};}
return results;});assert.match(result.renderer,/swiftshader/i,'Requested software backend must be observed');assert.equal(result.original.error,0);assert.equal(result.depth_initialized_control.error,0);assert.ok(Math.abs(result.original.before[1]-1)<1e-6);assert.ok(Math.abs(result.original.after[0]-.1)<1e-6,'Foreground emission must survive the real transfer depth buffer');assert.ok(Math.abs(result.original.after[0]-result.depth_initialized_control.after[0])<1e-7);await mkdir(path.dirname(output),{recursive:true});await writeFile(output,JSON.stringify({passed:true,scope:'Actual production fragment shader, depth-attached framebuffer, foreground Gaussian strand',...result},null,2));console.log(JSON.stringify({passed:true,...result}));}finally{await browser?.close();await new Promise(r=>server.close(r));}
